// This file will be auto-generated by Supabase CLI
// For now, we'll define a basic structure that matches our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      businesses: {
        Row: {
          id: string
          name: string
          slug: string
          email: string | null
          phone: string | null
          address: string | null
          timezone: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          email?: string | null
          phone?: string | null
          address?: string | null
          timezone?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          email?: string | null
          phone?: string | null
          address?: string | null
          timezone?: string
          created_at?: string
          updated_at?: string
        }
      }
      business_members: {
        Row: {
          id: string
          business_id: string
          user_id: string
          role: string
          created_at: string
        }
        Insert: {
          id?: string
          business_id: string
          user_id: string
          role?: string
          created_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          user_id?: string
          role?: string
          created_at?: string
        }
      }
      services: {
        Row: {
          id: string
          business_id: string
          name: string
          description: string | null
          duration_minutes: number
          price_cents: number | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          name: string
          description?: string | null
          duration_minutes?: number
          price_cents?: number | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          name?: string
          description?: string | null
          duration_minutes?: number
          price_cents?: number | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      staff: {
        Row: {
          id: string
          business_id: string
          name: string
          email: string | null
          phone: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          name: string
          email?: string | null
          phone?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          name?: string
          email?: string | null
          phone?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      staff_weekly_hours: {
        Row: {
          id: string
          staff_id: string
          day_of_week: number
          start_time: string
          end_time: string
          created_at: string
        }
        Insert: {
          id?: string
          staff_id: string
          day_of_week: number
          start_time: string
          end_time: string
          created_at?: string
        }
        Update: {
          id?: string
          staff_id?: string
          day_of_week?: number
          start_time?: string
          end_time?: string
          created_at?: string
        }
      }
      staff_time_off: {
        Row: {
          id: string
          staff_id: string
          start_time: string
          end_time: string
          reason: string | null
          created_at: string
        }
        Insert: {
          id?: string
          staff_id: string
          start_time: string
          end_time: string
          reason?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          staff_id?: string
          start_time?: string
          end_time?: string
          reason?: string | null
          created_at?: string
        }
      }
      customers: {
        Row: {
          id: string
          business_id: string
          name: string
          email: string | null
          phone: string | null
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          name: string
          email?: string | null
          phone?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          name?: string
          email?: string | null
          phone?: string | null
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      appointments: {
        Row: {
          id: string
          business_id: string
          customer_id: string
          service_id: string
          staff_id: string | null
          start_time: string
          end_time: string
          status: string
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          customer_id: string
          service_id: string
          staff_id?: string | null
          start_time: string
          end_time: string
          status?: string
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          customer_id?: string
          service_id?: string
          staff_id?: string | null
          start_time?: string
          end_time?: string
          status?: string
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      reviews: {
        Row: {
          id: string
          business_id: string
          customer_id: string | null
          source: string
          rating: number
          comment: string | null
          reviewer_name: string | null
          review_date: string | null
          sentiment: string | null
          created_at: string
        }
        Insert: {
          id?: string
          business_id: string
          customer_id?: string | null
          source: string
          rating: number
          comment?: string | null
          reviewer_name?: string | null
          review_date?: string | null
          sentiment?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          customer_id?: string | null
          source?: string
          rating?: number
          comment?: string | null
          reviewer_name?: string | null
          review_date?: string | null
          sentiment?: string | null
          created_at?: string
        }
      }
      review_summaries: {
        Row: {
          id: string
          business_id: string
          period_start: string
          period_end: string
          summary_text: string
          created_at: string
        }
        Insert: {
          id?: string
          business_id: string
          period_start: string
          period_end: string
          summary_text: string
          created_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          period_start?: string
          period_end?: string
          summary_text?: string
          created_at?: string
        }
      }
      churn_snapshots: {
        Row: {
          id: string
          business_id: string
          snapshot_date: string
          customer_id: string
          days_since_last_appointment: number | null
          total_appointments: number
          last_appointment_date: string | null
          is_churned: boolean
          created_at: string
        }
        Insert: {
          id?: string
          business_id: string
          snapshot_date: string
          customer_id: string
          days_since_last_appointment?: number | null
          total_appointments?: number
          last_appointment_date?: string | null
          is_churned?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          snapshot_date?: string
          customer_id?: string
          days_since_last_appointment?: number | null
          total_appointments?: number
          last_appointment_date?: string | null
          is_churned?: boolean
          created_at?: string
        }
      }
      churn_suggestions: {
        Row: {
          id: string
          business_id: string
          customer_id: string
          suggestion_text: string
          priority: string
          created_at: string
          viewed_at: string | null
        }
        Insert: {
          id?: string
          business_id: string
          customer_id: string
          suggestion_text: string
          priority?: string
          created_at?: string
          viewed_at?: string | null
        }
        Update: {
          id?: string
          business_id?: string
          customer_id?: string
          suggestion_text?: string
          priority?: string
          created_at?: string
          viewed_at?: string | null
        }
      }
      subscriptions: {
        Row: {
          id: string
          business_id: string
          stripe_subscription_id: string
          stripe_customer_id: string
          status: string
          current_period_start: string | null
          current_period_end: string | null
          cancel_at_period_end: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          stripe_subscription_id: string
          stripe_customer_id: string
          status: string
          current_period_start?: string | null
          current_period_end?: string | null
          cancel_at_period_end?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          stripe_subscription_id?: string
          stripe_customer_id?: string
          status?: string
          current_period_start?: string | null
          current_period_end?: string | null
          cancel_at_period_end?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      jobs: {
        Row: {
          id: string
          business_id: string
          type: string
          run_at: string
          status: 'pending' | 'processing' | 'succeeded' | 'failed' | 'cancelled'
          attempts: number
          max_attempts: number
          payload: Json
          last_error: string | null
          locked_at: string | null
          locked_by: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          business_id: string
          type: string
          run_at?: string
          status?: 'pending' | 'processing' | 'succeeded' | 'failed' | 'cancelled'
          attempts?: number
          max_attempts?: number
          payload?: Json
          last_error?: string | null
          locked_at?: string | null
          locked_by?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          business_id?: string
          type?: string
          run_at?: string
          status?: 'pending' | 'processing' | 'succeeded' | 'failed' | 'cancelled'
          attempts?: number
          max_attempts?: number
          payload?: Json
          last_error?: string | null
          locked_at?: string | null
          locked_by?: string | null
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      is_business_member: {
        Args: {
          bid: string
          uid: string
        }
        Returns: boolean
      }
    }
    Enums: {
      [_ in never]: never
    }
  }
}
